### ISSUE TITLE
Cannot detect audio format for some mp3 files.

### ISSUE THREAD

**Issue by T-vK** [audiojs/audio-decode#30]
My audio-decode version: 2.1.1
My MP3 file: [test.zip](https://github.com/audiojs/audio-decode/files/11170669/test.zip)
My code:

```
const fs = require('fs').promises;

async function main(options) {
    const audioDecode = await import('audio-decode');
    const decode = audioDecode.default;
    await audioDecode.decoders.mp3();
    const buffer = fs.readFile('test.mp3');
    const decodedBuffer = await decode(buffer);
}

main().catch(console.error)
```

I get the following error:

```
Error: Cannot detect audio format
    at audioDecode (file:///home/fedora/test/node_modules/audio-decode/audio-decode.js:17:19)
    at main (/home/fedora/test/test.js:8:33)
```

**Comment by dy** [comment]
Yeah, you forgot to wait for file load here `const buffer = fs.readFile('test.mp3');`, it must be a Promise, so just `const buffer = await fs.readFile('test.mp3');`.

**Comment by T-vK** [comment]
Sorry, my faul.
